//
// Created by michaelpollind on 9/27/21.
//

#ifndef AMNESIATHEDARKDESCENT_HPL2_CORE_INCLUDE_GRAPHICS_HPLSHADERGLOBAL_H
#define AMNESIATHEDARKDESCENT_HPL2_CORE_INCLUDE_GRAPHICS_HPLSHADERGLOBAL_H

#endif // AMNESIATHEDARKDESCENT_HPL2_CORE_INCLUDE_GRAPHICS_HPLSHADERGLOBAL_H
