//
// Created by michaelpollind on 9/25/21.
//

#ifndef AMNESIATHEDARKDESCENT_HPL2_CORE_INCLUDE_GRAPHICS_HPLTEXTURE_H
#define AMNESIATHEDARKDESCENT_HPL2_CORE_INCLUDE_GRAPHICS_HPLTEXTURE_H

class IHPLTexture {

};

class HPLTexture2d : public IHPLTexture {

};

#endif // AMNESIATHEDARKDESCENT_HPL2_CORE_INCLUDE_GRAPHICS_HPLTEXTURE_H
